import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const hooks={},active={electrical:false,emp:false},module={};let enabled=true;
const actor={uuid:'Actor.target',effects:[{name:'Electrical Shock',disabled:false,statuses:new Set()}]};
const combat={id:'combat',started:true,combatants:[{actor}],combatant:{actor:{uuid:'Actor.other'}}};
const game={modules:{get:()=>module},user:{character:actor},settings:{get:()=>enabled},combats:[combat],time:{worldTime:0}};
const context=vm.createContext({game,canvas:{tokens:{controlled:[]}},Hooks:{once:(k,f)=>hooks[k]=f,on:(k,f)=>hooks[k]=f,callAll(){}},document:{hidden:false,addEventListener(){}},window:{addEventListener(){}},createElectricalOverlay:kind=>({start:()=>active[kind]=true,stop:()=>active[kind]=false})});
vm.runInContext((await readFile('dist/electrical-effects.js','utf8')).replace(/^import .*;\s*/gm,'').replace(/export /g,'')+'\nregisterElectricalEffects();',context);
hooks.ready();assert.deepEqual(active,{electrical:false,emp:false},'no gameplay trigger installed');
module.api.activateElectricalEffect(actor,'electrical');module.api.activateElectricalEffect(actor,'emp');assert.deepEqual(active,{electrical:true,emp:true});
hooks.updateCombat(combat,{round:2});assert.equal(active.electrical,true);enabled=false;hooks.pneumaVisualToolsScreenEffectsChanged();assert.deepEqual(active,{electrical:false,emp:false});enabled=true;hooks.pneumaVisualToolsScreenEffectsChanged();assert.equal(active.emp,true);
combat.combatant={actor};hooks.updateCombat(combat,{turn:1});assert.deepEqual(active,{electrical:false,emp:false});hooks.controlToken();assert.equal(active.electrical,false);
game.combats=[];module.api.activateElectricalEffect(actor,'emp');game.time.worldTime=6;hooks.updateWorldTime();assert.equal(active.emp,false);
console.log('Prepared electrical/EMP API, deferred triggers, independent kinds and next-turn cleanup passed');
let applied=true;const original=game.modules.get;game.modules.get=id=>id==='pneuma-combattools'?{active:true,api:{hasActorEMP:()=>applied}}:original(id);
hooks.updateItem();assert.equal(active.emp,true,'existing applied Combat Tools EMP restores the screen overlay');assert.equal(vm.runInContext('hasEMP(game.user.character)',context),true,'token query reads the same applied state');
hooks.updateCombat(combat,{turn:2});assert.equal(active.emp,true,'applied EMP follows mechanical duration, not next-turn cleanup');
applied=false;hooks.updateItem();assert.equal(active.emp,false,'removal or expiry of actual disablement clears visuals');
