import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
const calls=[],loads=[];let init;
const context=vm.createContext({game:{settings:{get:()=>true}},registerEffectsPreview:()=>calls.push('previews'),registerRemainingEffects:()=>calls.push('remaining'),registerFireEffects:()=>calls.push('fire'),registerIntrusionEffects:()=>calls.push('intrusion'),registerFlashbangEffects:()=>calls.push('flashbang'),registerElectricalEffects:()=>calls.push('electrical'),registerSubstanceEffects:()=>calls.push('substances'),registerHumanityEffects:()=>calls.push('humanity'),registerTokenEffects:()=>calls.push('tokens'),registerVisualSettings:()=>calls.push('settings'),Hooks:{once:(name,callback)=>{assert.equal(name,'init');init=callback}},console:{info(){},error(){}},registerThemeCustomizer:()=>calls.push('theme'),registerScenePreviews:()=>calls.push('scenes'),registerAudioTools:()=>calls.push('audio'),registerWindowEscapeProtection:()=>calls.push('escape'),ensureChatStyles:()=>calls.push('styles'),registerChatCards:()=>calls.push('cards'),registerChatDice:()=>calls.push('dice'),registerChatDiceMenu:()=>calls.push('diceMenu'),loadFeature:async path=>{loads.push(path);assert.equal(path,'./weapon-effects.js');return {registerWeaponEffects:()=>calls.push('weapons')}}});
vm.runInContext((await readFile('dist/release-features.js','utf8')).replace(/export /g,''),context);
const source=(await readFile('dist/main.js','utf8')).replace(/^import .*;\s*/gm,'').replaceAll('import.meta.url',"'file:///module/main.js'").replaceAll('import(', 'loadFeature(');
vm.runInContext(source,context);const pending=init();assert.deepEqual(calls,['theme','settings','scenes','audio','escape','styles','cards','dice','diceMenu','substances','humanity','tokens','electrical','flashbang','remaining','fire','intrusion','previews'],'all settings register synchronously before init returns');await pending;assert.deepEqual(calls,['theme','settings','scenes','audio','escape','styles','cards','dice','diceMenu','substances','humanity','tokens','electrical','flashbang','remaining','fire','intrusion','previews','weapons']);assert.deepEqual(loads,['./weapon-effects.js']);
assert.equal(vm.runInContext('Object.isFrozen(RELEASE_FEATURES)',context),true);
assert.equal(vm.runInContext('RELEASE_FEATURES.weaponEffects',context),true);
for(const key of ['neuralIntrusion','fireEffects'])assert.equal(vm.runInContext(`RELEASE_FEATURES.${key}`,context),true);
console.log('Startup registers all implemented screen effects synchronously, including intrusion and fire.');

calls.length=0;context.game.settings.get=()=>false;await init();assert.ok(!calls.includes("scenes")&&!calls.includes("audio"));

calls.length=0;context.registerSubstanceEffects=()=>{throw Error('effect failure')};await init();assert.ok(calls.includes('cards')&&calls.includes('diceMenu')&&calls.includes('humanity')&&calls.includes('tokens')&&calls.includes('weapons'));console.log('Effect failure cannot suppress core settings or remaining features');
