import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
const calls=[],loads=[];let init;
const context=vm.createContext({Hooks:{once:(name,callback)=>{assert.equal(name,'init');init=callback}},console:{info(){}},registerThemeCustomizer:()=>calls.push('theme'),registerScenePreviews:()=>calls.push('scenes'),registerAudioTools:()=>calls.push('audio'),registerWindowEscapeProtection:()=>calls.push('escape'),ensureChatStyles:()=>calls.push('styles'),registerChatCards:()=>calls.push('cards'),registerChatDice:()=>calls.push('dice'),registerChatDiceMenu:()=>calls.push('diceMenu'),loadFeature:async path=>{loads.push(path);assert.equal(path,'./weapon-effects.js');return {registerWeaponEffects:()=>calls.push('weapons')}}});
vm.runInContext((await readFile('dist/release-features.js','utf8')).replace(/export /g,''),context);
const source=(await readFile('dist/main.js','utf8')).replace(/^import .*;\s*/gm,'').replaceAll('import.meta.url',"'file:///module/main.js'").replaceAll('import(', 'loadFeature(');
vm.runInContext(source,context);await init();assert.deepEqual(calls,['theme','scenes','audio','escape','styles','cards','dice','diceMenu','weapons']);assert.deepEqual(loads,['./weapon-effects.js']);
assert.equal(vm.runInContext('Object.isFrozen(RELEASE_FEATURES)',context),true);
assert.equal(vm.runInContext('RELEASE_FEATURES.weaponEffects',context),true);
for(const key of ['neuralIntrusion','fireEffects'])assert.equal(vm.runInContext(`RELEASE_FEATURES.${key}`,context),false);
console.log('Startup registers combat effects; intrusion and fire remain disabled.');
