import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
let smashActive=false;
const hooks={},settings=new Map([['screenEffects',{scope:'client',onChange:()=>hooks.pneumaVisualToolsScreenEffectsChanged()}]]),active={poison:false,blueGlass:false};
const effect={name:'Blue Glass',disabled:false,isSuppressed:false,statuses:new Set(),duration:{seconds:14400,startTime:0}};
const actor={uuid:'Actor.player',effects:[effect],isOwner:true};
const other={uuid:'Actor.other'};
const combat={id:'combat',started:true,combatants:[{actor},{actor:other}],combatant:{actor:other}};
const game={settings:{get:(m,k)=>settings.get(k)?.enabled!==false,register:(m,k,v)=>settings.set(k,v)},user:{character:actor},combats:[combat],time:{worldTime:0}};
const context=vm.createContext({game,canvas:{tokens:{controlled:[]}},Hooks:{callAll(){},once:(k,f)=>hooks[k]=f,on:(k,f)=>hooks[k]=f},document:{hidden:false,addEventListener(){}},window:{addEventListener(){}},createSmashScreenOverlay:()=>({start:()=>smashActive=true,stop:()=>smashActive=false}),createSubstanceOverlay:kind=>({start:()=>active[kind]=true,stop:()=>active[kind]=false})});
vm.runInContext((await readFile('dist/substance-effects.js','utf8')).replace(/^import .*;\s*/gm,'').replace(/export /g,'')+'\nregisterSubstanceEffects();',context);
hooks.ready();assert.equal(active.blueGlass,true);
hooks.pneumaCombatToolsExposure(actor.uuid,'poison');assert.equal(active.poison,true);
hooks.updateCombat(combat,{round:2});assert.equal(active.poison,true,'other turn across round boundary retains poison');
combat.combatant={actor};hooks.updateCombat(combat,{turn:1});assert.equal(active.poison,false);
hooks.updateActor();assert.equal(active.poison,false,'sync cannot rearm cleared exposure');
hooks.pneumaCombatToolsExposure(other.uuid,'poison');assert.equal(active.poison,false);
hooks.pneumaCombatToolsExposure(actor.uuid,'poison');hooks.deleteCombat(combat);assert.equal(active.poison,false);
effect.disabled=true;hooks.updateActiveEffect();assert.equal(active.blueGlass,false);
effect.disabled=false;hooks.updateActiveEffect();assert.equal(active.blueGlass,true);
game.time.worldTime=14400;hooks.updateWorldTime();assert.equal(active.blueGlass,false);
game.combats=[];hooks.pneumaCombatToolsExposure(actor.uuid,'poison');assert.equal(active.poison,true);game.time.worldTime+=6;hooks.updateWorldTime();assert.equal(active.poison,false);
game.time.worldTime=0;hooks.updateWorldTime();settings.get('screenEffects').enabled=false;settings.get('screenEffects').onChange();assert.equal(active.blueGlass,false);
hooks.canvasTearDown();assert.deepEqual(active,{poison:false,blueGlass:false});
settings.get('screenEffects').enabled=true;game.combats=[combat];combat.combatant={actor:other};
const nativePoison={name:'Poisoned',statuses:new Set(['poisoned']),disabled:false,isSuppressed:false};actor.effects.push(nativePoison);
hooks.controlToken();assert.equal(active.poison,true,'existing native poisoned effect is hydrated without a new event');
combat.combatant={actor};hooks.updateCombat(combat,{turn:2});assert.equal(active.poison,false);
hooks.controlToken();assert.equal(active.poison,false,'persistent native marker cannot rearm after next turn');
nativePoison.disabled=true;hooks.updateActiveEffect();nativePoison.disabled=false;combat.combatant={actor:other};hooks.updateActiveEffect();assert.equal(active.poison,true,'new native activation rearms');
hooks.deleteCombat(combat);nativePoison.disabled=true;hooks.updateActiveEffect();
let monitored=true;game.modules={get:()=>({active:true,api:{hasMonitorExposure:()=>monitored}})};
hooks.controlToken();assert.equal(active.poison,true,'existing Combat Tools monitor exposure is hydrated');
combat.combatant={actor};hooks.updateCombat(combat,{turn:3});hooks.controlToken();assert.equal(active.poison,false,'monitor round hold cannot override next-turn cleanup');
monitored=false;hooks.updateActor();
actor.effects=[];actor.items=[{effects:[{name:'Blue Glass Primary',disabled:false,isSuppressed:false,statuses:new Set(),duration:{}}]}];
hooks.updateItem();assert.equal(active.blueGlass,true,'native item primary effect activates without a token marker');
actor.items[0].effects[0].disabled=true;hooks.updateActiveEffect();assert.equal(active.blueGlass,false,'unused drug does not activate');
actor.items[0].effects[0].disabled=false;actor.items[0].effects[0].name='Blue Glass Addiction';hooks.updateItem();assert.equal(active.blueGlass,false,'addiction alone does not activate trip');
actor.items[0].effects[0].name='Blue Glass Primary Effect';hooks.updateItem();assert.equal(active.blueGlass,true);
actor.items[0].effects[0].system={isSuppressed:true};hooks.updateItem();assert.equal(active.blueGlass,false);
let saved=true;game.modules={get:()=>({active:true,api:{hasReportedExposure:()=>saved,hasMonitorExposure:()=>true}})};
hooks.controlToken();assert.equal(active.poison,true,'saved combat exposure restores screen state');
combat.combatant={actor};hooks.updateCombat(combat,{turn:4});saved=false;hooks.updateActor();assert.equal(active.poison,false,'expired saved exposure overrides stale monitor');
actor.items=[{effects:[{name:'Smash Primary',disabled:false,statuses:new Set(),duration:{}}]}];hooks.updateItem();assert.equal(smashActive,true);actor.items[0].effects[0].name='Smash Addiction';hooks.updateItem();assert.equal(smashActive,false);actor.items[0].effects[0].name='Smash Primary';actor.items[0].effects[0].disabled=true;hooks.updateItem();assert.equal(smashActive,false);
actor.items=[{effects:[{name:'Synthcoke Addicted Primary',disabled:false,statuses:new Set(),duration:{}}]}];assert.equal(vm.runInContext("hasPrimaryDrug(game.user.character,'Synthcoke','bsixucw55vezxc66')",context),true,'addiction-aware primary is active drug use');actor.items[0].effects[0].name='Synthcoke Addiction';assert.equal(vm.runInContext("hasPrimaryDrug(game.user.character,'Synthcoke','bsixucw55vezxc66')",context),false);
console.log('Substance exposure, next-turn cleanup, targeting, expiry and toggles passed');
